site_name: utia-gc/ngs
site_url: https://utia-gc.github.io/ngs/

theme:
  name: material

  palette:
  # Palette toggle for light mode
    - media: "(preferes-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  # Palette toggle for dark mode
    - media: "(preferes-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # Navigation features: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top

    # Site search features: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
    - search.highlight
    - search.share

plugins:
  - search
