site_name: utia-gc/ngs
site_url: https://utia-gc.github.io/ngs/

theme:
  name: material

  palette:
  # Palette toggle for light mode
    - media: "(preferes-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  # Palette toggle for dark mode
    - media: "(preferes-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.indexes
