title: utia-gc/ngs
description: A Nextflow pipeline for base NGS analysis.
theme: just-the-docs

url: https://utia-gc.github.io

aux_links:
  utia-gc/ngs on GitHub: https://github.com/utia-gc/ngs

plugins:
  - jekyll-relative-links
